package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 收藏夹表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Collectors implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 收藏夹编号. */
	private Integer COLLECT_ID;

	/** 收藏时间. */
	private String TIME;
	
	/** 收藏类型. */
	private String TYPE;
	
	/** 分类名称. */
	private Integer GOODS_ID;

	/** 商品编号. */
	private String USER_ID;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Collectors() {
	}

	/**
	 * 收藏夹编号 傪愝掕偟傑偡.
	 * 
	 * @param COLLECT_ID
	 *            收藏夹编号
	 */
	public void setCOLLECT_ID(Integer COLLECT_ID) {
		this.COLLECT_ID = COLLECT_ID;
	}

	/**
	 * 收藏夹编号 傪庢摼偟傑偡.
	 * 
	 * @return 收藏夹编号
	 */
	public Integer getCOLLECT_ID() {
		return this.COLLECT_ID;
	}

	/**
	 * 收藏时间 傪愝掕偟傑偡.
	 * 
	 * @param TIME
	 *            收藏时间
	 */
	public void setTIME(String TIME) {
		this.TIME = TIME;
	}

	/**
	 * 收藏时间 傪庢摼偟傑偡.
	 * 
	 * @return 收藏时间
	 */
	public String getTIME() {
		return this.TIME;
	}

	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param classify
	 *            分类名称
	 */
	public void setTYPE(String TYPE) {
		this.TYPE = TYPE;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getTYPE() {
		return this.TYPE ;
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param GOODS_ID
	 *            商品编号
	 */
	public void setGOODS_ID(Integer GOODS_ID) {
		this.GOODS_ID = GOODS_ID;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getGOODS_ID() {
		return this.GOODS_ID;
	}
	
	/**
	 * 分类名称 傪愝掕偟傑偡.
	 * 
	 * @param USER_ID
	 *            分类名称
	 */
	public void setUSERS_ID(String USERS_ID) {
		this.USER_ID = USER_ID;
	}

	/**
	 * 分类名称 傪庢摼偟傑偡.
	 * 
	 * @return 分类名称
	 */
	public String getUSERS_ID() {
		return this.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((COLLECT_ID == null) ? 0 : COLLECT_ID.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Collectors other = (Collectors) obj;
		if (COLLECT_ID == null) {
			if (other.COLLECT_ID != null) {
				return false;
			}
		} else if (!COLLECT_ID.equals(other.COLLECT_ID)) {
			return false;
		}

		return true;
	}

}
