package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 商品表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Goods implements Serializable {

	@Override
	public String toString() {
		return "Goods [goods_id=" + goods_id + ", gname=" + gname
				+ ", type=" + type + ", price=" + price
				+ ", sum=" + sum + ", image=" + image
				+ "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商品编号. */
	private Integer goods_id;

	/** 商品名称. */
	private String gname;

	/** 商品类型. */
	private String type;

	/** 商品价格. */
	private Double price;

	/** 商品数量. */
	private Integer sum;

	/** 商品图片. */
	private String image;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Goods() {
	}

	/**
	 * 商品编号 傪愝掕偟傑偡.
	 * 
	 * @param goods_id
	 *            商品编号
	 */
	public void setgoods_id(Integer goods_id) {
		this.goods_id = goods_id;
	}

	/**
	 * 商品编号 傪庢摼偟傑偡.
	 * 
	 * @return 商品编号
	 */
	public Integer getgoods_id() {
		return this.goods_id;
	}

	/**
	 * 商品名称 傪愝掕偟傑偡.
	 * 
	 * @param gname
	 *            商品名称
	 */
	public void setgname(String gname) {
		this.gname = gname;
	}

	/**
	 * 商品名称 傪庢摼偟傑偡.
	 * 
	 * @return 商品名称
	 */
	public String getgname() {
		return this.gname;
	}

	/**
	 * 商品类型 傪愝掕偟傑偡.
	 * 
	 * @param type
	 *            商品类型
	 */
	public void settype(String type) {
		this.type = type;
	}

	/**
	 * 商品类型 傪庢摼偟傑偡.
	 * 
	 * @return 商品类型
	 */
	public String gettype() {
		return this.type;
	}

	/**
	 * 商品价格 傪愝掕偟傑偡.
	 * 
	 * @param price
	 *            商品价格
	 */
	public void setprice(Double price) {
		this.price = price;
	}

	/**
	 * 商品价格 傪庢摼偟傑偡.
	 * 
	 * @return 商品价格
	 */
	public Double getprice() {
		return this.price;
	}

	/**
	 * 商品数量 傪愝掕偟傑偡.
	 * 
	 * @param sum
	 *            商品数量
	 */
	public void setsum(Integer sum) {
		this.sum = sum;
	}

	/**
	 * 商品数量 傪庢摼偟傑偡.
	 * 
	 * @return 商品数量
	 */
	public Integer getsum() {
		return this.sum;
	}

	/**
	 * 商品图片 傪愝掕偟傑偡.
	 * 
	 * @param image
	 *            商品图片
	 */
	public void setimage(String image) {
		this.image = image;
	}

	/**
	 * 商品图片 傪庢摼偟傑偡.
	 * 
	 * @return 商品图片
	 */
	public String getimage() {
		return this.image;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((goods_id == null) ? 0 : goods_id.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Goods other = (Goods) obj;
		if (goods_id == null) {
			if (other.goods_id != null) {
				return false;
			}
		} else if (!goods_id.equals(other.goods_id)) {
			return false;
		}

		return true;
	}

}
