package com.oracle.shop.model.javabean;

import java.io.Serializable;

/**
 * 订单表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Orders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 订单编号. */
	private String orders_id;

	/** 下单时间. */
	private String ordertime;

	/** 订单状态. */
	private String status;

	/** 收货地址. */
	private String adresses;

	/** 备注. */
	private String mark;
	/** 备注. */
	private String shouhuoname;

	/** 用户编号. */
	private Integer users_id;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Orders() {
	}

	/**
	 * 订单编号 傪愝掕偟傑偡.
	 * 
	 * @param orderid
	 *            订单编号
	 */
	public void setOrderid(String orderid) {
		this.orders_id = orderid;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public String getOrderid() {
		return this.orders_id;
	}
	public void setshouhuoname(String shouhuoname) {
		this.shouhuoname = shouhuoname;
	}

	/**
	 * 订单编号 傪庢摼偟傑偡.
	 * 
	 * @return 订单编号
	 */
	public String getshouhuoname() {
		return this.shouhuoname;
	}
	/**
	 * 下单时间 傪愝掕偟傑偡.
	 * 
	 * @param ordertime
	 *            下单时间
	 */
	public void setordertime(String ordertime) {
		this.ordertime = ordertime;
	}

	/**
	 * 下单时间 傪庢摼偟傑偡.
	 * 
	 * @return 下单时间
	 */
	public String getordertime() {
		return this.ordertime;
	}

	/**
	 * 订单状态 傪愝掕偟傑偡.
	 * 
	 * @param status
	 *            订单状态
	 */
	public void setstatus(String status) {
		this.status = status;
	}

	/**
	 * 订单状态 傪庢摼偟傑偡.
	 * 
	 * @return 订单状态
	 */
	public String getstatus() {
		return this.status;
	}

	/**
	 * 收货地址 傪愝掕偟傑偡.
	 * 
	 * @param adresses
	 *            收货地址
	 */
	public void setadresses(String adresses) {
		this.adresses = adresses;
	}

	/**
	 * 收货地址 傪庢摼偟傑偡.
	 * 
	 * @return 收货地址
	 */
	public String getadresses() {
		return this.adresses;
	}

	/**
	 * 备注 傪愝掕偟傑偡.
	 * 
	 * @param mark
	 *            备注
	 */
	public void setmark(String mark) {
		this.mark = mark;
	}

	/**
	 * 备注 傪庢摼偟傑偡.
	 * 
	 * @return 备注
	 */
	public String getmark() {
		return this.mark;
	}
	public String shouhuoname() {
		return this.shouhuoname;
	}
	/**
	 * 用户编号 傪愝掕偟傑偡.
	 * 
	 * @param users_id
	 *            用户编号
	 */
	public void setusers_id(Integer users_id) {
		this.users_id = users_id;
	}

	/**
	 * 用户编号 傪庢摼偟傑偡.
	 * 
	 * @return 用户编号
	 */
	public Integer getusers_id() {
		return this.users_id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orders_id == null) ? 0 : orders_id.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Orders other = (Orders) obj;
		if (orders_id == null) {
			if (other.orders_id != null) {
				return false;
			}
		} else if (!orders_id.equals(other.orders_id)) {
			return false;
		}

		return true;
	}

}
